### ISSUE TITLE
20201216 TODO

### ISSUE THREAD

**Issue by lljj-x** [lljj-x/vue-json-schema-form#25]
- [x]  Widget 组件 存在 enumOptions 配置，必须是 required 时才做默认选中
- [x] 考虑 配置 widget ref ，方便直接获取到 widget 组件实例
- [x] ui:hidden: false 文档错误问题
