### ISSUE TITLE
TODO: next-version

### ISSUE THREAD

**Issue by lljj-x** [lljj-x/vue-json-schema-form#45]
### features:
- [ ] 支持 Schema 依赖 - `low`
- [ ] 完善 Object   additionalProperties 支持 - `low`
- [x] #79
- [x] #84 
- [x] 对 Widget 添加onChange props，接收parentData、rootFormData (可能打破jsonSchema)

### features:
- [x] `不需要` ~~适配多ui库后，默认会注册相同名称的全局组件，考虑同时支持 vue.use 安装，支持传入组件前缀以示区分~~
- [x] `已发布` ~~支持 readonly 属性~~
- [x] 添加title回退到属性名配置 #54 
- [x] 优化vue3 antd 默认color picker样式 #52

### bugs:
- [x] ~~vue3 elementPlus dateTimeRange 区间选择，数据回填默认值写入不成功，鼠标hover即可恢复，待查element源码确`element 新版本已修复`~~ 
- [x] `已发布` ~~优化 upload 上传组件和bug解决 #50~~
- [x] #105
- [x] #104
- [x] 支持 slots配置 #84 
- [x] 支持 emits的配置 #84

**Comment by xgenvn** [comment]
嗨， 请问与react-jsonschema-form有关吗？ 我看`uiSchema`很类似，但是不知道能支持多少

**Comment by lljj-x** [comment]
@xgenvn  参考过他的设计，但相关配置不一样
